string = "python is a case sensitive language"
# (a)
print(len(string))
# (b)
print(string[::-1])
# (c)
print(string[10:26])
# (d)
string1 = string.replace("a case sensitive","object oriented")
print(string1)
# (e)
x = string.index("a")
print(x)
# (f)
y = string.strip()
print(y)